#!/usr/bin/env bash

## Initialize Grav site
##
## Just do it!

# Console colors
red='\033[0;91m'
red_bg='\033[101m'
yellow_bg='\033[43m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-green () { echo -e "${green}$1${NC}"; }

_confirm () 
{
	while true; do
		echo -en "$1 (y/n): "
		read -p "" answer
		case "$answer" in
			[Yy]|[Yy][Ee][Ss] )
				break
				;;
			[Nn]|[Nn][Oo] )
				[[ "$2" == "--no-exit" ]] && return 1
				exit 1
				;;
			* )
				echo 'Please answer yes or no.'
		esac
	done
}

# --- Runtime ---


cd "$PROJECT_ROOT"

# Revert all changes
if [[ "$(git status -z)" != "" ]]; then
	_confirm "${yellow}You have local changes${NC} (see git status). Re-install is going to remove them. \nContinue?${NC}"
  git checkout .
  git clean -fd .
fi

# Start the project
fin start

echo -e "${green_bg}DONE${NC}"
echo-green "Login to your Grav site Admin UI."
echo -e "  URL:      ${yellow}http://${VIRTUAL_HOST}/admin${NC}"
echo -e "  Username: ${yellow}admin${NC}"
echo -e "  Password: ${yellow}Passw0rd${NC}"
echo
